# Generated by Django 2.2.7 on 2022-01-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terremoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Magnitud', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('Lugar', models.CharField(max_length=100, null=True)),
                ('Tiempo', models.DateField(null=True)),
                ('Tsunami', models.IntegerField(default=0, null=True)),
                ('Importancia', models.IntegerField(null=True)),
                ('Fecha_Actualizacion', models.DateField(null=True)),
                ('Alerta', models.CharField(max_length=100, null=True)),
                ('Dispersion_profundidad', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Tipo_Movimiento', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
