# Generated by Django 2.2.7 on 2022-01-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terremotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terremoto',
            options={'verbose_name': 'Terremoto', 'verbose_name_plural': 'Terremotos'},
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Alerta',
            new_name='alerta',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Dispersion_profundidad',
            new_name='dispersion_profundidad',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Fecha_Actualizacion',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Importancia',
            new_name='importancia',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Lugar',
            new_name='lugar',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Magnitud',
            new_name='magnitud',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Tiempo',
            new_name='tiempo',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Tipo_Movimiento',
            new_name='tipo_movimiento',
        ),
        migrations.RenameField(
            model_name='terremoto',
            old_name='Tsunami',
            new_name='tsunami',
        ),
    ]
