# Generated by Django 2.2.7 on 2022-01-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terremotos', '0002_auto_20220104_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terremoto',
            name='dispersion_profundidad',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='terremoto',
            name='magnitud',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
