# Generated by Django 2.2.7 on 2022-01-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terremotos', '0003_auto_20220104_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terremoto',
            name='dispersion_profundidad',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='terremoto',
            name='magnitud',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
