# Generated by Django 2.2.7 on 2022-01-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terremotos', '0004_auto_20220104_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terremoto',
            name='dispersion_profundidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='terremoto',
            name='magnitud',
            field=models.FloatField(null=True),
        ),
    ]
