# Generated by Django 2.2.7 on 2022-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terremotos', '0005_auto_20220104_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='terremoto',
            name='profundidad',
            field=models.FloatField(null=True),
        ),
    ]
