# Generated by Django 2.2.7 on 2022-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terremotos', '0006_terremoto_profundidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terremoto',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
